apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: akstodonodejs3
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: akstodonodejs3
    spec:
      containers:
      - name: pdtacr
        image: pdtacr.azurecr.io/todowcosmos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: adsacr-auth
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: akstodonodejs3
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: akstodonodejs3
